### ISSUE TITLE
Test failures on vapoursynth-api-36 on VapourSynth R57

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/vapoursynth-rs#15]
VapourSynth R57 fails `vapoursynth-api-36` tests across all OSes. Windows says it's `STATUS_STACK_BUFFER_OVERRUN`: https://github.com/YaLTeR/vapoursynth-rs/runs/4850789438?check_suite_focus=true#step:6:7231

VapourSynth R53 works fine, so the error started happening somewhere after R53.

**Comment by quietvoid** [comment]
I've looked at the backtrace and it's aborting when running `test-vpy/pixel-formats.vpy`.
Both tests using the script fail the same way.

There's apparently a panic in `add_message_handler_trivial::c_callback`, which causes the abort.

I'll try to look more into it later but this is the backtrace:

```
#0  0x00007ffff7b9f34c in __pthread_kill_implementation () at /usr/lib/libc.so.6
#1  0x00007ffff7b524b8 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff7b3c534 in abort () at /usr/lib/libc.so.6
#3  0x0000555555637ac7 in std::sys::unix::abort_internal () at library/std/src/sys/unix/mod.rs:259
#4  0x000055555556f906 in std::process::abort () at library/std/src/process.rs:1993
#5  0x00005555555ba04a in vapoursynth::api::{impl#2}::add_message_handler_trivial::c_callback
    (msg_type=1, msg=0x7fffcc01e490, user_data=0x5555555ae070 <core::ops::function::FnOnce::call_once<vapoursynth::tests::need_api::add_message_handler::{closure#1}, (vapoursynth::api::MessageType, &std::ffi::c_str::CStr)>>) at vapoursynth/src/api.rs:385
        closure = core::panic::unwind_safe::AssertUnwindSafe<vapoursynth::api::{impl#2}::add_message_handler_trivial::c_callback::{closure#0}> (
          vapoursynth::api::{impl#2}::add_message_handler_trivial::c_callback::{closure#0} {
            _ref__msg_type: 0x7ffff5741f6c,
            _ref__msg: 0x7ffff5741f70,
            _ref__user_data: 0x7ffff5741f78
          }
        )
#6  0x00007ffff7ebf17c in vsLog3(vs3::VSMessageType, char const*, ...) (type=vs3::mtWarning, msg=0x7ffff7f5b77d "%s") at ../vapoursynth/src/core/vslog.cpp:90
        iter = {
          first = 1,
          second = {
            handler = 0x5555555b9f40 <vapoursynth::api::{impl#2}::add_message_handler_trivial::c_callback>,
            free = 0x0,
            userData = 0x5555555ae070 <core::ops::function::FnOnce::call_once<vapoursynth::tests::need_api::add_message_handler::{closure#1}, (vapoursynth::api::MessageType, &std::ffi::c_str::CStr)>>
          }
        }
        __for_range = std::map with 1 element = {
          [1] = {
            handler = 0x5555555b9f40 <vapoursynth::api::{impl#2}::add_message_handler_trivial::c_callback>,
            free = 0x0,
            userData = 0x5555555ae070 <core::ops::function::FnOnce::call_once<vapoursynth::tests::need_api::add_message_handler::{closure#1}, (vapoursynth::api::MessageType, &std::ffi::c_str::CStr)>>
          }
        }
        alist = {typedef __va_list_tag __va_list_tag {
            gp_offset: 24,
            fp_offset: 48,
            overflow_arg_area: 0x7ffff5742150,
            reg_save_area: 0x7ffff5742060
          }}
        size = 180
        lock = {
          _M_device = @0x7ffff7f8a0e0: std::mutex {
            std::__mutex_base: std::__mutex_base {
              _M_mutex: pthread_mutex_t {
                __data: __pthread_mutex_s {
                  __lock: 1,
                  __count: 0,
                  __owner: 391735,
                  __nusers: 1,
                  __kind: 0,
                  __spins: 0,
                  __elision: 0,
                  __list: __pthread_internal_list {
                    __prev: 0x0,
                    __next: 0x0
                  }
                },
                __size: [1, 0, 0, 0, 0, 0, 0, 0, 55, -6, 5, 0, 1, 0 <repeats 27 times>],
                __align: 1
              }
            }
          }
        }
#7  0x00007ffff7eae73d in VSCore::logMessage(VSMessageType, char const*)
    (this=0x7fffcc00bf40, type=mtWarning, msg=0x7ffff43e4ad0 "test-vpy/pixel-formats.vpy:16: DeprecationWarning: register_format() is deprecated. Use \"query_video_format\" instead.\n  format = core.register_format(vs.YUV, vs.INTEGER, 17, 0, 0)\n")
    at ../vapoursynth/src/core/vscore.cpp:1275
--Type <RET> for more, q to quit, c to continue without paging--
        lock = {
          _M_device = @0x7fffcc00c098: std::mutex {
            std::__mutex_base: std::__mutex_base {
              _M_mutex: pthread_mutex_t {
                __data: __pthread_mutex_s {
                  __lock: 1,
                  __count: 0,
                  __owner: 391735,
                  __nusers: 1,
                  __kind: 0,
                  __spins: 0,
                  __elision: 0,
                  __list: __pthread_internal_list {
                    __prev: 0x0,
                    __next: 0x0
                  }
                },
                __size: [1, 0, 0, 0, 0, 0, 0, 0, 55, -6, 5, 0, 1, 0 <repeats 27 times>],
                __align: 1
              }
            }
          }
        }
#8  0x00007ffff7e9e0ca in logMessage(int, char const*, VSCore*) (msgType=<optimized out>, msg=<optimized out>, core=<optimized out>) at ../vapoursynth/src/core/vsapi.cpp:879
```

**Comment by quietvoid** [comment]
They both pass when disabling the `add_message_handler` test, and it only fails with the `add_message_handler_trivial` block.
Maybe something isn't being cleared properly?

It seems to be that `setMessageHandler` doesn't clear the handler anymore. Not sure if it ever did.

**Comment by YaLTeR** [comment]
```
#7  0x00007ffff7eae73d in VSCore::logMessage(VSMessageType, char const*)
    (this=0x7fffcc00bf40, type=mtWarning, msg=0x7ffff43e4ad0 "test-vpy/pixel-formats.vpy:16: DeprecationWarning: register_format() is deprecated. Use \"query_video_format\" instead.\n  format = core.register_format(vs.YUV, vs.INTEGER, 17, 0, 0)\n")
```

Seems like this warning is coming from another test? That'll certainly break the message handler test, it assumes there are no other messages concurrently.

**Comment by quietvoid** [comment]
> Seems like this warning is coming from another test? 

Yes it is.

One way I've fixed it is to simply replace the `clear_message_handler()` call by `remove_message_handler`

**Comment by YaLTeR** [comment]
Ah, I guess if it runs on API level 36 and above anyway, we can use `remove_message_handler`.

When that test was originally made, there was no `remove_message_handler` yet IIRC, and also some bugs with `add_message_handler` (hence the commented out version of the test above with a warning message).

**Comment by YaLTeR** [comment]
Of course that still won't help if another test posts a warning exactly as the test is running. Maybe it could be extracted to a separate binary?

**Comment by quietvoid** [comment]
I haven't been able to get the issue after fixing the handler clear so far.
It does seem to me that being static, the sender is still in memory but the receiver was dropped.

**Comment by YaLTeR** [comment]
>  It does seem to me that being static, the sender is still in memory but the receiver was dropped.

That's true, but as long as the message handler is cleared it should never be called.

> I haven't been able to get the issue after fixing the handler clear so far.

It might be a tricky timing to hit. I guess I can fix it when it actually happens.
